### ISSUE TITLE
Build: issues with linking isl (graphite.c, gcc)

### ISSUE THREAD

**Issue by tallero** [ps2dev/ps2toolchain-ee#25]
Hello, I'm [upstreaming](https://github.com/ps2dev/ps2sdk/issues/387) the ps2dev repositories to AUR and I'm having issues building the stage2 gcc, with `graphite.c` not finding `isl` includes.

Same thing happens on both `ee-v11.3.0` and `ee-v10.2.0` branches, with host compilers `gcc12` and `gcc7`.

Please take a look at the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mips64r5900el-ps2-elf-gcc) for `mips64r5900el-ps2-elf-gcc`.

[build.log](https://github.com/ps2dev/ps2toolchain-ee/files/10335944/build.log)

**Comment by tallero** [comment]
Ok, so installing `mips64r5900el-pthread-embedded`, which currently overwrites files from `mips64r6900el-pthread-embedded` seems to make it able to build.
Could you help me determine why the linker is not able to link headers from an alternative location?

**Comment by uyjulian** [comment]
Probably required for multi stage build

This doesn't seem to be an issue anymore. Reopen if this is not the case
