### ISSUE TITLE
Keep getting this error, not sure how to fix..

### ISSUE THREAD

**Issue by djinijd** [ps2dev/ps2toolchain-ee#40]
../scripts/001-binutils.sh: Failed.
../scripts/002-iop.sh: Failed.
../scripts/001-toolchain.sh: Failed.

**Comment by djinijd** [comment]
I'm using ubuntu 22.04.3

**Comment by fjtrujy** [comment]
Closing this issue, please, reopen whenever you add more info.

Cheers.
