### ISSUE TITLE
Enable Link Time Optimizations

### ISSUE THREAD

**Issue by leidav** [ps2dev/ps2toolchain-ee#6]
I noticed that the install script disables LTO in gcc completely. Is there a specific reason for it?
LTO support could reduce binary sizes dramatically, especially in projects that make heavy use of modern c++ features.

**Comment by rickgaiser** [comment]
In an effor to reduce the size of the new toolchain, all features we thought where not used have been disabled.

I don't know much about Link Time Optimization. Would enabling this in the toolchain result in smaller binaries automatically, or do we need to pass special flags (like -flto) and do other special stuff to get any advantage out of this feature?

**Comment by leidav** [comment]
It would only have an effect if you pass the -flto flag to the compiler. LTO  increases compile times considerable. I'm not sure if it would make sense to build the ps2sdk and newlib with -flto enabled as a default option.
But if all libraries and the program is compiled that way, the final executable would only contain the used functions (in some situations even inlined). 

I never tried to use LTO between multiple libraries or even inside  libc. I think to use that feature we need to use mips64r5900el-ps2-elf-gcc-ar instead of mips64r5900el-ps2-elf-ar, as this loads the correct plugin needed by the linker to produce an LTO enabled library.
But even if it isn't used by ps2sdk or newlib itself, it would be a great option for a program or game that wants  to get the most out of the PS2 hardware.

**Comment by fjtrujy** [comment]
Hello @leidav,
In the #7, we enabled the LTO, so I will close this PR.

Enjoy 😄 !
